Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore

@inirudy
chukmunnlee
/
cfdsa-mar29-2022
Public
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
cfdsa-mar29-2022/demo04/dov-deploy.yaml
@chukmunnlee
chukmunnlee day4 AM demos
Latest commit 1c0192b 1 minute ago
History
1 contributor
67 lines (65 sloc)  1.22 KB
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  labels:
    name: dov-cm
data:
  INSTANCE_NAME: dov-cm-bear

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  labels:
    name: dov-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      name: dov-pod
  template:
    metadata:
      name: dov-pod
      labels:
        name: dov-pod
        dept: engg
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  name: dov-pod
                  dept: engg
              topologyKey: doks.digitalocean.com/node-id
      containers:
        - name: dov-container
          image: stackupiss/dov-bear:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: INSTANCE_HASH
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: dov-cm
          ports:
            - name: dov-port
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  labels:
    name: dov-svc
spec:
  type: ClusterIP
  selector:
    name: dov-pod
  ports:
    - port: 8080
      targetPort: dov-port
