---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dov-netpol-deny-all
  labels:
    name: dov-netpol-deny-all
spec:
  podSelector:
    matchLabels:
      name: dov-pod
  policyTypes:
    - Ingress
