apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-cm
  labels:
    name: bggapp-cm
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggappv1-deploy
  labels:
    name: bggappv1-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggappv1-pod
  template:
    metadata:
      name: bggappv1-pod
      labels:
        name: bggappv1-pod
        dept: app
    spec:
      containers:
        - name: bggappv1-container
          image: stackupiss/bgg-backend:v1
          args:
            - --prefix
            - /v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: bggapp-cm
            - secretRef:
                name: bgg-secret
          ports:
            - name: bggappv1-port
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggappv1-svc
  labels:
    name: bggappv1-svc
spec:
  type: ClusterIP
  selector:
    name: bggappv1-pod
  ports:
    - port: 80
      targetPort: bggappv1-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggappv2-deploy
  labels:
    name: bggappv2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggappv2-pod
  template:
    metadata:
      name: bggappv2-pod
      labels:
        name: bggappv2-pod
        dept: app
    spec:
      containers:
        - name: bggappv2-container
          image: stackupiss/bgg-backend:v2
          args:
            - --prefix
            - /v2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: bggapp-cm
            - secretRef:
                name: bgg-secret
          ports:
            - name: bggappv2-port
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggappv2-svc
  labels:
    name: bggappv2-svc
spec:
  type: ClusterIP
  selector:
    name: bggappv2-pod
  ports:
    - port: 80
      targetPort: bggappv2-port
