apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-cm
  labels:
    name: bggapp-cm
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: bggapp-pod
  template:
    metadata:
      name: bggapp-pod
      labels:
        name: bggapp-pod
        dept: app
    spec:
      containers:
        - name: bggapp-container
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: bggapp-cm
            - secretRef:
                name: bgg-secret
          ports:
            - name: bggapp-port
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bggapp-pod
  ports:
    - port: 80
      targetPort: bggapp-port
