apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-cm
  labels:
    name: bggapp-cm
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local:8080
  BGG_DB_PASSWORD: changeit

---
apiVersion: v1
kind: Pod
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
spec:
  containers:
    - name: bggapp-container
      image: stackupiss/bgg-backend:v1
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: bggapp-cm
      ports:
        - name: bggapp-port
          containerPort: 3000
